name: Docker Build and Push to ACR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PUSH_ACR }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: projetombaacr.azurecr.io

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t cnes-pipeline .

      - name: Tag Docker image
        run: |
          docker tag cnes-pipeline projetombaacr.azurecr.io/cnes-pipeline:latest

      - name: Push image to ACR
        run: |
          docker push projetombaacr.azurecr.io/cnes-pipeline:latest

          
      - name: Logout of Azure
        run: az logout

